version: '2.0'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./database/mysql:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_ROOT_PASSWORD=password
    ports:
    - "3306:3306"
  phpmyadmin:
     image: phpmyadmin/phpmyadmin:4.7
     restart: always
     links:
       - mysql
     ports:
       - 8081:80
     environment:
       - MYSQL_USERNAME=root
       - MYSQL_ROOT_PASSWORD=password
       - PMA_HOST=mysql
  web:
    build: .
    volumes:
      - .:/usr/src/blog-server-express
    ports:
      - "1337:1337"
    depends_on:
      - mysql
#    command: gulp
  nginx:
    restart: always
    image: nginx:1.13.8
    volumes:
      - ./config/nginx/sites-enabled:/etc/nginx/sites-enabled
    ports:
      - "81:80"
    links:
      - web:web
    depends_on:
      - web
volumes:
  blog-server-express: