version: '2.0'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./blog-server-express:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_ROOT_PASSWORD=password
    ports:
    - "3306:3306"
  phpmyadmin:
     image: phpmyadmin/phpmyadmin:4.7
     restart: always
     links:
       - mysql
     ports:
       - 8081:80
     environment:
       - MYSQL_USERNAME=root
       - MYSQL_ROOT_PASSWORD=password
       - PMA_HOST=mysql
  web:
    build: .
    volumes:
      - .:/usr/src/blog-server-express
    ports:
      - "1337:1337"
    depends_on:
      - mysql
  nginx:
    build: ./config/nginx/
    ports:
      - "80:80"
    restart: always
    volumes_from:
      - web
    links:
      - web:web
volumes:
  blog-server-express: